package com.zjx.opensource.interfaceviewer.mapper;

import com.zjx.opensource.interfaceviewer.model.Interface;
import com.zjx.opensource.interfaceviewer.model.InterfaceExample;
import java.util.List;

import com.zjx.opensource.interfaceviewer.model.InterfaceVO;
import org.apache.ibatis.annotations.Param;

public interface InterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    long countByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    int deleteByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    int insert(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    int insertSelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    List<Interface> selectByExample(InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    Interface selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Interface record, @Param("example") InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Interface record, @Param("example") InterfaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Interface record);

    List<InterfaceVO> selectByProjectId(@Param("projectId") int projectId,@Param("name") String nameLike,@Param("start") long start,@Param("end") long end);

    InterfaceVO selectById(@Param("id") int interfaceId);
}